#ifndef MYSOCKET_H
#define MYSOCKET_H

#define LISTEN_QUEQUE_SIZE 20

#define ERROR_SOCKET_CREATION -301
#define ERROR_SOCKET_SET_REUSEADD_OPTION -302
#define ERROR_SOCKET_TCP_CORK -303
#define ERROR_SOCKET_BINDING -304
#define ERROR_SOCKET_LISTEN -305

int get_sockfd(const int port);

#endif // MYSOCKET_H
